import { Component, OnInit } from '@angular/core';
import { User } from './modules/users/model/user.model';
import * as _localStorage from './utilities/local-storage/local-storage';
import { Task } from './modules/tasks/model/task.model';
import { RoleEnum } from './modules/users/model/user.model';
import { TaskStatusEnum } from './modules/tasks/model/task.model';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  constructor() {
    const user: User[] = [
      {
        lastName: 'Eden',
        firstName: 'John',
        username: 'John1',
        email: 'john@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.Admin,
      },
      {
        lastName: 'Doe',
        firstName: 'Jane',
        username: 'JaneDoe',
        email: 'jane@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Smith',
        firstName: 'Robert',
        username: 'Rob123',
        email: 'robert@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Johnson',
        firstName: 'Emily',
        username: 'EmiJoh',
        email: 'emily@yahoo.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Garcia',
        firstName: 'Maria',
        username: 'MariaG',
        email: 'maria@gmail.com',
        password: '123456',
        organization: {
          name: 'Garcia Enterprises',
          phoneNumber: '+5555555555',
          address: '101 Pine St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Brown',
        firstName: 'David',
        username: 'DavidBrown',
        email: 'david@gmail.com',
        password: '123456',
        organization: {
          name: 'Garcia Enterprises',
          phoneNumber: '+5555555555',
          address: '101 Pine St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Wilson',
        firstName: 'Lisa',
        username: 'LisaW',
        email: 'lisa@yahoo.com',
        password: '123456',
        organization: {
          name: 'Garcia Enterprises',
          phoneNumber: '+5555555555',
          address: '101 Pine St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Lee',
        firstName: 'Michael',
        username: 'MikeLee',
        email: 'mike@gmail.com',
        password: '123456',
        organization: {
          name: 'Lee Enterprises',
          phoneNumber: '+4444444444',
          address: '777 Cedar St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Jackson',
        firstName: 'Sarah',
        username: 'SJackson',
        email: 'sarah@gmail.com',
        password: '123456',
        organization: {
          name: 'Jackson Corp',
          phoneNumber: '+7777777777',
          address: '999 Pine St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Martinez',
        firstName: 'Daniel',
        username: 'DanM',
        email: 'dan@yahoo.com',
        password: '123456',
        organization: {
          name: 'Jackson Corp',
          phoneNumber: '+7777777777',
          address: '999 Pine St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Harris',
        firstName: 'Jessica',
        username: 'JessH',
        email: 'jessica@gmail.com',
        password: '123456',
        organization: {
          name: 'Jackson Corp',
          phoneNumber: '+7777777777',
          address: '999 Pine St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Clark',
        firstName: 'Kevin',
        username: 'KClark',
        email: 'kevin@gmail.com',
        password: '123456',
        organization: {
          name: 'Clark Co.',
          phoneNumber: '+5555555555',
          address: '888 Maple Ave',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Lewis',
        firstName: 'Megan',
        username: 'MegLewis',
        email: 'megan@yahoo.com',
        password: '123456',
        organization: {
          name: 'White Group',
          phoneNumber: '+5555555555',
          address: '888 Maple Ave',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Anderson',
        firstName: 'Matthew',
        username: 'MattA',
        email: 'matthew@gmail.com',
        password: '123456',
        organization: {
          name: 'Anderson Inc',
          phoneNumber: '+3333333333',
          address: '555 Cedar St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Taylor',
        firstName: 'Jennifer',
        username: 'JenT',
        email: 'jennifer@gmail.com',
        password: '123456',
        organization: {
          name: 'Taylor Enterprises',
          phoneNumber: '+1111111111',
          address: '222 Pine St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Moore',
        firstName: 'Andrew',
        username: 'AndyM',
        email: 'andy@gmail.com',
        password: '123456',
        organization: {
          name: 'Taylor Enterprises',
          phoneNumber: '+1111111111',
          address: '222 Pine St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'White',
        firstName: 'Olivia',
        username: 'OliviaW',
        email: 'olivia@yahoo.com',
        password: '123456',
        organization: {
          name: 'White Group',
          phoneNumber: '+2222222222',
          address: '111 Oak St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Lopez',
        firstName: 'Christopher',
        username: 'ChrisL',
        email: 'chris@gmail.com',
        password: '123456',
        organization: {
          name: 'White Group',
          phoneNumber: '+2222222222',
          address: '111 Oak St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Hill',
        firstName: 'Lauren',
        username: 'LaurenH',
        email: 'lauren@gmail.com',
        password: '123456',
        organization: {
          name: 'Hill Ltd.',
          phoneNumber: '+5555555555',
          address: '777 Pine St',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Doe1',
        firstName: 'Jane1',
        username: 'JaneDoe1',
        email: 'jane1@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Doe2',
        firstName: 'Jane2',
        username: 'JaneDoe2',
        email: 'jane2@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Doe3',
        firstName: 'Jane3',
        username: 'JaneDoe3',
        email: 'jane3@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Doe4',
        firstName: 'Jane4',
        username: 'JaneDoe5',
        email: 'jane5@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Doe6',
        firstName: 'Jane6',
        username: 'JaneDoe6',
        email: 'jane6@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Doe7',
        firstName: 'Jane7',
        username: 'JaneDoe7',
        email: 'jane7@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Doe8',
        firstName: 'Jane8',
        username: 'JaneDoe8',
        email: 'jane8@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Doe9',
        firstName: 'Jane9',
        username: 'JaneDoe9',
        email: 'jane9@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Doe10',
        firstName: 'Jane10',
        username: 'JaneDoe10',
        email: 'jane10@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Doe11',
        firstName: 'Jane11',
        username: 'JaneDoe11',
        email: 'jane11@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
      {
        lastName: 'Doe12',
        firstName: 'Jane12',
        username: 'JaneDoe12',
        email: 'jane12@gmail.com',
        password: '123456',
        organization: {
          name: 'John Company',
          phoneNumber: '+999000000000',
          address: 'some',
        },
        role: RoleEnum.User,
      },
    ];

    const tasks: Task[] = [
      {
        creator: 'JaneDoe1',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Inprogress,
      },
      {
        creator: 'JaneDoe2',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Todo,
      },
      {
        creator: 'JaneDoe3',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Inprogress,
      },
      {
        creator: 'JaneDoe4',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Done,
      },
      {
        creator: 'JaneDoe5',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Done,
      },
      {
        creator: 'JaneDoe6',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Done,
      },
      {
        creator: 'JaneDoe7',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Done,
      },
      {
        creator: 'JaneDoe8',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Done,
      },
      {
        creator: 'JaneDoe9',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Done,
      },
      {
        creator: 'JaneDoe10',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Done,
      },
      {
        creator: 'JaneDoe11',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Done,
      },
      {
        creator: 'JaneDoe12',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Done,
      },
      {
        creator: 'JaneDoe13',
        organizationName: 'John Company',
        title: 'any title',
        description: 'any description',
        deadline: '2023-09-14',
        assignedUsers: [
          'JaneDoe1',
          'JaneDoe2',
          'John1',
          'JaneDoe3',
          'JaneDoe4',
          'JaneDoe5',
          'JaneDoe6',
          'JaneDoe7',
          'JaneDoe8',
          'JaneDoe9',
          'JaneDoe10',
          'JaneDoe11',
          'JaneDoe12',
          'JaneDoe13',
        ],
        status: TaskStatusEnum.Done,
      },
    ];

    if (!_localStorage.hasItem('users')) {
      _localStorage.setItem('users', user);
    }
    if (!_localStorage.hasItem('task-list')) {
      _localStorage.setItem('task-list', tasks);
    }
  }
}
